name: Deploy

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm install -g parcel-bundler
      - run: parcel build index.html
      - uses: actions/upload-artifact@master
        with:
          name: bundled
          path: dist

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@master
        with:
          name: bundled
          path: dist
      - run: mkdir ~/.ssh
      - run: git config --global user.email "niels.warncke@gmail.com"
      - run: echo $SSH_KEY > ~/.ssh/id_rsa
      - run: chmod 600 ~/.ssh/id_rsa
      - run: wc -l ~/.ssh/id_rsa
      - run: git clone git@github.com:nielsrolf/nielsrolf.github.io.git
      - run: cp nielsrolf.github.io/README.md .
      - run: cp -r dist/* nielsrolf.github.io/
      - run: cp -r README.md nielsrolf.github.io/README.md
      - run: cd nielsrolf.github.io && git add . && git commit -m "Automated build update" && git push --set-upstream origin master

